# Generated by Django 2.2.4 on 2019-08-21 14:30

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('P', 'Processing'), ('F', 'Failed'), ('C', 'Completed')], default='P', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FileEntitiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', django_mysql.models.JSONField(default=dict)),
                ('object_status', models.CharField(choices=[('F', 'Found'), ('N', 'Not Found')], default='F', max_length=2)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.Archive')),
            ],
        ),
    ]
